#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time    : 17/3/17 上午10:27
# @Author  : chenshuangyan

"""主题信息"""

# 招行配置
# MONGO_CONFIG = {
#     'host': '99.240.10.137',
#     'port': 40042,
#     'db': 'final_data',
#     'username': 'work',
#     'password': 'haizhi',
# }

# 海致配置
MONGO_CONFIG = {
    'host': '172.16.215.16',
    'port': 40042,
    'db': 'app_data',
    'username': 'work',
    'password': 'haizhi'
}

CHECK_DATES = 6

CHECK_TOPIC = {
    "enterprise_data_gov": {"description": "工商信息变更", "tag": u"离线抓取", "sites": [
        {"site": "bj.gsxt.gov.cn"}, {"site": "tj.gsxt.gov.cn"}, {"site": "he.gsxt.gov.cn"}, {"site": "sx.gsxt.gov.cn"},
        {"site": "nm.gsxt.gov.cn"}, {"site": "ln.gsxt.gov.cn"}, {"site": "jl.gsxt.gov.cn"}, {"site": "hl.gsxt.gov.cn"},
        {"site": "sh.gsxt.gov.cn"}, {"site": "www.jsgsj.gov.cn"}, {"site": "zj.gsxt.gov.cn"},
        {"site": "ah.gsxt.gov.cn"},
        {"site": "jx.gsxt.gov.cn"}, {"site": "fj.gsxt.gov.cn"}, {"site": "sd.gsxt.gov.cn"}, {"site": "gd.gsxt.gov.cn"},
        {"site": "gx.gsxt.gov.cn"}, {"site": "hi.gsxt.gov.cn"}, {"site": "ha.gsxt.gov.cn"}, {"site": "hb.gsxt.gov.cn"},
        {"site": "hn.gsxt.gov.cn"}, {"site": "cq.gsxt.gov.cn"}, {"site": "sc.gsxt.gov.cn"}, {"site": "gz.gsxt.gov.cn"},
        {"site": "yn.gsxt.gov.cn"}, {"site": "xz.gsxt.gov.cn"}, {"site": "sn.gsxt.gov.cn"}, {"site": "gs.gsxt.gov.cn"},
        {"site": "qh.gsxt.gov.cn"}, {"site": "nx.gsxt.gov.cn"}, {"site": "xj.gsxt.gov.cn"}
    ]},
    "court_ktgg": {"description": "开庭公告", "tag": u"离线抓取", "sites": [
        {"name": "江苏南通崇川区人民法院", "site": "58.221.162.249", },
        {"name": "北京法院－审判信息网(开庭公告-全量离线抓取，裁判文书-离线抓取)", "site": "www.bjcourt.gov.cn", },
        {"name": "山东法院审判流程公开平台", "site": "www.sdcourt.gov.cn", },
        {"name": "广东法院网", "site": "www.gdcourts.gov.cn", "ignore": True, "tag": u"请求不到数据"},
        {"name": "重庆法院公众服务网（裁判文书-全量离线灌库）", "site": "www.cqfygzfw.com", },
        {"name": "江苏南京中级人民法院网", "site": "www.njfy.gov.cn"},
        {"name": "重庆市南岸人民法院", "site": "www.cqnafy.gov.cn", "ignore": True, "tag": u"开庭公告只有201601以前的，后续没更新"},
        {"name": "江苏法院庭审直播网", "site": "js.sifayun.com", },
        {"name": "开庭公告-安徽芜湖", "site": "whyjfy.chinacourt.org", },
        {"name": "合肥市蜀山区人民法院", "site": "www.sscourt.gov.cn", "ignore": True, "tag": u"实体解析不支持"},
        {"name": "庐阳区人民法院", "site": "www.luyang.gov.cn", "ignore": True, "tag": u"需要实体解析"},
        {"name": "开庭公告-安徽庐江县人民法院", "site": "fy.lj.gov.cn", "ignore": True, "tag": u"站点无法访问"},
        {"name": "铜陵市中级人民法院", "site": "www.tlcourt.gov.cn", "ignore": True, "tag": u"数据全以p标签堆在一起，没有分列，难以解析"},
        {"name": "浙江法院公开网（裁判文书-全量离线灌库）", "site": "www.zjsfgkw.cn", },
        {"name": "开庭公告-福建莆田", "site": "ptcxqfy.chinacourt.org", "ignore": True, "tag": u"数据杂乱不规范"},
        {"name": "www.pdfy.gov.cn", "site": "www.pdfy.gov.cn", "ignore": True, "tag": u"站点无法访问"},
        {"name": "开庭公告-海南椰城法律网", "site": "www.hkfy.gov.cn", },
        {"name": "天涯法律网视", "site": "tv.hicourt.gov.cn", },
        {"name": "海南藏族自治州人民法院", "site": "qhhnzy.chinacourt.org", "ignore": True, "tag": u"大部分为非开庭公告内容不入库"},
        {"name": "开庭公告-海南（裁判文书-全量离线灌库）", "site": "www.hicourt.gov.cn", },
        {"name": "武汉市汉江区人民法院", "site": "jhqfy.hbfy.gov.cn", "ignore": True, "tag": u"配置规则问题(只有2015-09前的内容，后续都没更新)"},
        {"name": "武汉市中级人民法院", "site": "whzy.hbfy.gov.cn", "ignore": True, "tag": u"数据全以p标签堆在一起，没有分列，难以解析"},
        {"name": "湖南法院网", "site": "hunanfy.chinacourt.org", },
        {"name": "开庭公告-湖南长沙法院网", "site": "cszy.chinacourt.org", "ignore": True, "tag": u"站点数据由单数据换成了表格和文档"},
        {"name": "开庭公告-河南法院庭审直播网", "site": "ts.hncourt.gov.cn", },
        {"name": "开庭公告-河南", "site": "www.hncourt.gov.cn", },
        {"name": "河南法院诉讼网", "site": "ssfw.hncourt.gov.cn", },
        {"name": "郑州法院诉讼服务网", "site": "www.zzfyssfw.gov.cn", },
        {"name": "江西南昌市中级人民法院", "site": "nczy.chinacourt.org", "ignore": True, "tag": u"站点无法打开"},
        {"name": "开庭公告-江西法院审判综合服务平台", "site": "www.jxfy.gov.cn", "ignore": True, "tag": u"站点封禁"},
        {"name": "开庭公告-天津河西", "site": "hxqfy.chinacourt.org", "ignore": True, "tag": u"数据全以p标签堆在一起，没有分列，难以解析"},
        {"name": "开庭公告-河北法院", "site": "hbgy.hbsfgk.org", },
        {"name": "121.28.181.179:7000", "site": "121.28.181.179:7000", "ignore": True, "tag": u"站点无法访问"},
        {"name": "开庭公告-山西太原", "site": "tyzy.chinacourt.org", },
        {"name": "山西省阳泉中级人民法院", "site": "yqzy.chinacourt.org", "ignore": True, "tag": u"数据全以p标签堆在一起，没有分列"},
        {"name": "开庭公告-山西朔州市中级人民法院", "site": "sxszzy.chinacourt.org", },
        {"name": "青海法院审判信息网（裁判文书-离线抓取）", "site": "www.qhcourt.gov.cn", },
        {"name": "开庭公告-陕西法院庭审直播网", "site": "www.sxgaofa.cn", "ignore": True, "tag": u"实体解析暂时无法支持"},
        {"name": "甘肃省高级人民法院司法公开网", "site": "gsgf.gssfgk.com", },
        {"name": "四川法院司法公开网", "site": "pzh.sccourt.gov.cn", },
        {"name": "开庭公告-云南法院司法信息网", "site": "www.ynfy.gov.cn", },
        {"name": "辽宁省高级人民法院司法公开网", "site": "www.lnsfy.gov.cn", },
        {"name": "吉林省高级人民法院司法公开网（裁判文书-离线抓取）", "site": "www.jlsfy.gov.cn", },
        {"name": "开庭公告-牡丹江市中级人民法院网", "site": "mdjzy.hljcourt.gov.cn", },
        {"name": "黑龙江法院网", "site": "www.hljcourt.gov.cn", },
        {"name": "广西法院阳光司法网", "site": "171.106.48.55", "ignore": True, "tag": u"站点无法访问"},
        {"name": "南宁法院网", "site": "nnzy.chinacourt.org", },
        {"name": "宁夏法院网", "site": "www.nxfy.gov.cn", },
        {"name": "开庭公告-新疆兵团", "site": "117.190.16.231", },
        {"name": "开庭公告-西藏高级人民法院", "site": "xzgy.susong51.net", },
        {"name": "开庭公告-全国庭审公开网", "site": "tingshen.court.gov.cn", },
        {"name": "中华人民共和国最高法院法", "site": "courtapp.chinacourt.org"},
        {"name": "广东法院网", "site": "www.gdcourts.gov.cn", "ignore": True, "tag": u"网页请求不到数据"},
        {"name": "江苏法院庭审直播网", "site": "js.sifayun.com", },
        {"name": "浙江法院公开网", "site": "www.zjsfgkw.cn", },
        {"name": "山东高级人民法院", "site": "www.sdcourt.gov.cn", },
        {"name": "上海市高级人民法院网", "site": "www.hshfy.sh.cn", },
        {"name": "福建省高级人民法院", "site": "www.fjcourt.gov.cn", },
        {"name": "湖北省高级人民法院", "site": "www.hbfy.gov.cn", },
        {"name": "北京法院网", "site": "bjgy.chinacourt.org", },
        {"name": "北京法院审判信息网", "site": "www.bjcourt.gov.cn", },
        {"name": "辽宁高级人民法院", "site": "218.60.146.92", },
        {"name": "四川法院网上诉讼服务中心", "site": "zxgk.sccourt.gov.cn", },
        {"name": "河南省高级人民法院", "site": "www.hncourt.gov.cn", },
        {"name": "江西法院审判综合服务平台", "site": "www.jxfy.gov.cn", "ignore": True, "tag": u"官方声明禁止爬取"},
        {"name": "天津法院网", "site": "101.201.34.59"},
        {"name": "陕西法院网", "site": "sxfy.chinacourt.org", },
        {"name": "湖南法院网", "site": "hunanfy.chinacourt.org", },
        {"name": "安徽法院诉讼服务网", "site": "www.ahgyss.cn", },
        {"name": "重庆法院公众服务网", "site": "www.cqfygzfw.com", },
        {"name": "云南法院司法信息网", "site": "www.ynfy.gov.cn", },
        {"name": "河北法院网", "site": "hbgy.hbsfgk.org", },
        {"name": "黑龙江法院网", "site": "www.hljcourt.gov.cn", },
        {"name": "甘肃省高级人民法院司法公开网", "site": "gsgf.gssfgk.com", },
        {"name": "山西省高级人民法院", "site": "shanxify.chinacourt.org", "ignore": True, "tag": u"无开庭公告内容"},
        {"name": "吉林高院司法公开网", "site": "www.jlsfy.gov.cn", },
        {"name": "内蒙古法院网", "site": "nmgfy.chinacourt.org", "ignore": True, "tag": u"无开庭公告板块"},
        {"name": "新疆法院诉讼服务网", "site": "www.xjcourt.gov.cn", },
        {"name": "贵州法院网", "site": "www.guizhoucourt.cn", },
        {"name": "广西法院阳光司法网", "site": "171.106.48.55", "ignore": True, "tag": u"站点无法访问"},
        {"name": "宁夏法院网", "site": "www.nxfy.gov.cn", },
        {"name": "青海法院审判信息网", "site": "www.qhcourt.gov.cn", },
        {"name": "海南天涯法律网视", "site": "tv.hicourt.gov.cn", },
        {"name": "海南天涯法律网", "site": "www.hicourt.gov.cn", },
        {"name": "西藏自治区高级人民法院", "site": "xzgy.susong51.net", },
        {"name": "兵团法院庭审直播网", "site": "117.190.16.231"},
    ]},
    "shixin_info": {"description": "失信被执行人、曝光台", "sites": [
        {"name": "中国执行信息公开网", "site": "shixin.court.gov.cn", },
    ]},
    "judgement_wenshu": {"description": "裁判文书", "sites": [
        {"name": "上海市高级人民法院网(裁判文书-离线抓取)", "site": "www.hshfy.sh.cn", "ignore": True, "tag": u"网页反爬"},
        {"name": "南宁法院网", "site": "nnzy.chinacourt.org", "ignore": True, "tag": u"数据不曾更新，且内容为js复杂渲染"},
        {"name": "裁判文书-贵州法院网", "site": "58.16.66.85", "ignore": True, "tag": u"离线抓取，招行网络内无法访问"},
        {"name": "湖南法院网", "site": "hunanfy.chinacourt.org", "ignore": True, "tag": u"可以入库，但源站点上最近无数据更新"},
        {"name": "广东法院网", "site": "www.gdcourts.gov.cn", "ignore": True, "tag": u"有反爬，会先获取token再访问"},
        {"name": "裁判文书-新疆法院诉讼服务网", "site": "220.171.35.30", "ignore": True, "tag": u"非中文站点"},
        {"name": "重庆法院公众服务网（裁判文书-全量离线灌库）", "site": "www.cqfygzfw.com"},
        {"name": "诉讼无忧网（裁判文书-离线抓取）", "site": "www.susong51.com"},
        {"name": "湖北审判流程", "site": "www.hbfy.org"},
        {"name": "浙江法院公开网（裁判文书-全量离线灌库）", "site": "www.zjsfgkw.cn"},
        {"name": "福建省高级人民法院（裁判文书-全量离线灌库）", "site": "www.fjcourt.gov.cn", "ignore": True, "tag": u"内容页为乱码"},
        {"name": "青海法院审判信息网（裁判文书-离线抓取）", "site": "www.qhcourt.gov.cn", "ignore": True, "tag": u"可以入库，但源站点最近无数据更新"},
        {"name": "辽宁省高级人民法院司法公开网", "site": "www.lnsfy.gov.cn"},
        {"name": "佛山市中级人民法院（开庭公告-全量离线灌库）", "site": "www.fszjfy.gov.cn", "ignore": True, "tag": u"站点无法访问"},
        {"name": "辽宁省沈阳市中级人民法院", "site": "syzy.chinacourt.org", "ignore": True, "tag": u"站点无法访问"},
        {"name": "东莞市中级人民法院", "site": "www.dgcourt.gov.cn"},
        {"name": "江西南昌市中级人民法院", "site": "nczy.chinacourt.org", "ignore": True, "tag": u"站点无文书内容"},
        {"name": "广西法院阳光司法网", "site": "171.106.48.55"},
        {"name": "呼和浩特市中级人民法院", "site": "hhhtzy.chinacourt.org", "ignore": True, "tag": u"站内无文书内容"},
        {"name": "诉讼服务-天津法院网", "site": "tjfyold.chinacourt.org"},
        {"name": "新厦门法院网", "site": "www.xmcourt.gov.cn"},
        {"name": "北京法院－审判信息网(开庭公告-全量离线抓取，裁判文书-离线抓取)", "site": "www.bjcourt.gov.cn"},
        {"name": "南通法院网", "site": "www.ntfy.gov.cn"},
        {"name": "成都法院司法公开网", "site": "119.6.84.165"},
        {"name": "东莞法院诉讼服务中心", "site": "120.86.191.112", "ignore": True, "tag": u"需要检索"},
        {"name": "裁判文书抓取－中国裁判文书网", "site": "wenshu.court.gov.cn"},
        {"name": "开庭公告-海南（裁判文书-全量离线灌库）", "site": "www.hicourt.gov.cn"},
        {"name": "深圳法院网上诉讼服务平台", "site": "ssfw.szcourt.gov.cn", "ignore": True, "tag": u"内容特别大,且有验证码"},
        {"name": "北京法院网", "site": "bjgy.chinacourt.org", "ignore": True, "tag": u"站点无文书数据"},
        {"name": "吉林省高级人民法院司法公开网（裁判文书-离线抓取）", "site": "www.jlsfy.gov.cn"},
    ]},
    "bulletin": {"description": "法院公告", "sites": [
        {"name": "辽宁高级人民法院", "site": "lnfy.chinacourt.org", "ignore": True, "tag": u"该站点法院公告都是法院新闻"},
        {"name": "人民法院公告网", "site": "rmfygg.court.gov.cn"},
    ]},
    "zhixing_info": {"description": "执行信息", "sites": [
        {"name": "执行信息", "site": "zhixing.court.gov.cn"},
        {"name": "浙江法院公开网（裁判文书-全量离线灌库）", "site": "www.zjsfgkw.cn"},
        {"name": "山东法院审判流程公开平台", "site": "www.sdcourt.gov.cn", "ignore": True, "tag": u"站点上无执行信息"},
        {"name": "上海市高级人民法院网(裁判文书-离线抓取)", "site": "www.hshfy.sh.cn", "ignore": True, "tag": u"网页反爬"},
        {"name": "北京法院－审判信息网(开庭公告-全量离线抓取，裁判文书-离线抓取)", "site": "www.bjcourt.gov.cn", "ignore": True,
         "tag": u"实际数据为失信被执行人"},
        {"name": "四川法院网上诉讼服务中心", "site": "zxgk.sccourt.gov.cn"},
        {"name": "天津法院网", "site": "101.201.34.58", "ignore": True, "tag": u"站点存在验证码"},
        {"name": "开庭公告－陕西法院网", "site": "sxfy.chinacourt.org", "ignore": True, "tag": u"没有解析规则，站点目前没有执行公告"},
        {"name": "湖南法院网", "site": "hunanfy.chinacourt.org", "ignore": True,
         "tag": u"执行公告url与开庭公告格式完全一致，抓取系统无法区分，且需要实体解析"},
        {"name": "开庭公告-安徽法院诉讼服务网", "site": "www.ahgyss.cn", "ignore": True, "tag": u"站点实际为失信被执行人"},
        {"name": "重庆法院公众服务网（裁判文书-全量离线灌库）", "site": "www.cqfygzfw.com", "ignore": True, "tag": u"站点上无执行信息，实际为失信被执行人"},
        {"name": "开庭公告-云南法院司法信息网", "site": "www.ynfy.gov.cn", "ignore": True, "tag": u"站点上无执行信息，实际为失信被执行人"},
        {"name": "开庭公告-河北法院", "site": "hbgy.hbsfgk.org", "ignore": True, "tag": u"被执行信息无法访问"},
        {"name": "诉讼无忧网（裁判文书-离线抓取）", "site": "www.susong51.com", "ignore": True, "tag": u"服务已到期"},
        {"name": "甘肃省高级人民法院司法公开网", "site": "gsgf.gssfgk.com", "ignore": True, "tag": u"站点没有被执信数据"},
        {"name": "吉林省高级人民法院司法公开网（裁判文书-离线抓取）", "site": "www.jlsfy.gov.cn:8080", "ignore": True,
         "tag": u"所给网页无法访问，站点被执行信息链接到中国执行信息公开网"},
        {"name": "裁判文书-新疆法院诉讼服务网", "site": "220.171.35.30:8080", "ignore": True, "tag": u"所给网页无法访问，站点执行信息无法访问"},
        {"name": "裁判文书-贵州法院网", "site": "58.16.66.85:81", "ignore": True, "tag": u"站点无法访问"},
        {"name": "广西法院阳光司法网", "site": "171.106.48.55:18897", "ignore": True, "tag": u"站点无法访问"},
        {"name": "青海法院审判信息网（裁判文书-离线抓取）", "site": "www.qhcourt.gov.cn:8080", "ignore": True, "tag": u"站点无法访问"},
        {"name": "开庭公告-海南（裁判文书-全量离线灌库）", "site": "www.hicourt.gov.cn", "ignore": True,
         "tag": u"站点不稳定经常500，被执行信息不规范，为一个表格中不定位置，公告的表格格式不统一"},
        {"name": "开庭公告-西藏高级人民法院", "site": "xzgy.susong51.net", "ignore": True, "tag": u"数据更新频率低，源网页可能最近几天无数据更新"},
    ]},
    "judge_process": {"description": "审判流程", "sites": [
        {'name': '东莞市中级人民法院', 'site': 'www.dgcourt.gov.cn'},
        {'name': '审判流程-广东惠州', 'site': '120.24.17.155'},
        {'name': '湖北审判流程', 'site': 'www.hbfy.org', "ignore": True, "tag": u"phantomjs不稳定，需要重抓"},
        {'name': '浙江法院公开网（裁判文书-全量离线灌库）', 'site': 'www.zjsfgkw.cn'},
        {'name': '江苏南京中级人民法院网', 'site': 'www.njfy.gov.cn'},
    ]},
    "enterprise_owing_tax": {"description": "enterprise_owing_tax", "sites": [
        {'name': '欠税信息-北京地方税务局', 'site': 'shiju.tax861.gov.cn'},
        {'name': '欠税信息-江苏扬州税务局', 'site': 'yz.jsds.gov.cn', "ignore": True, "tag": u"实体解析不支持"},
        {'name': '广东省国家税务局', 'site': 'www.gd-n-tax.gov.cn', "ignore": True, "tag": u"欠税企业查询查到的列表，具体数据为excel文件"},
        {'name': '欠税信息-福建地方税务局', 'site': 'www.fj-l-tax.gov.cn'},
        {'name': '广东省地方税务局(离线)', 'site': 'www.gdltax.gov.cn'},
        {'name': '浙江省国家税务', 'site': 'www.zjtax.gov.cn', "ignore": True, "tag": u"需要用纳税人识别号查询"},
        {'name': '江苏省地方税务', 'site': 'pub.jsds.gov.cn', "ignore": True, "tag": u"表格为复杂表格，一个公司对应不确定的多个税种"},
        {'name': '上海市国家税务局', 'site': 'www.tax.sh.gov.cn', "ignore": True, "tag": u"表格为复杂表格，一个公司对应不确定的多个税种，切排列在多个td中"},
        {'name': '厦门市税务局', 'site': 'www.xm-n-tax.gov.cn', "ignore": True, "tag": u"没有欠税列表"},
    ]},
    "penalty": {"description": "行政处罚", "sites": [
        {'name': '行政处罚-上海市环境保护局', 'site': 'www.sepb.gov.cn'},
        {'name': '行政处罚-山东济南工商管理', 'site': 'www.jngsj.gov.cn'},
        {'name': '辽宁信用网', 'site': 'gsxt.lngs.gov.cn', "ignore": True, "tag": u"站点无法访问"},
        {'name': '行政处罚-中国信用网', 'site': 'www.creditchina.gov.cn'},
        {'name': '行政处罚-江苏省张家港市', 'site': 'credit.zjg.gov.cn', "ignore": True, "tag": u"站点无法访问"},
        {'name': '行政处罚-广东食品药品监督局', 'site': 'www.gdda.gov.cn'},
        {'name': '行政处罚-安徽滁州市食品药品安全', 'site': 'chuz.ada.gov.cn'},
        {'name': '工商抓取-湖南', 'site': 'gsxt.hnaic.gov.cn', "ignore": True, "tag": u"站点无法访问"},
        {'name': '行政处罚-江西政府信息公开', 'site': 'xxgk.jiangxi.gov.cn'},
        {'name': '行政处罚-河北食品药品监督局', 'site': 'www.hebfda.gov.cn'},
        {'name': '行政处罚-江西食品药品监督局', 'site': 'www.jxda.gov.cn', "ignore": True, "tag": u"详情页为文档和表格混合，不支持解析，不能入库"},
        {'name': '行政处罚-上海食品安全（2）', 'site': 'www.shfda.gov.cn'},
        {'name': '行政处罚-四川成都食品药品监督局', 'site': 'www.cdfda.gov.cn'},
        {'name': '行政处罚-河南郑州食品药品监督局', 'site': 'public.zhengzhou.gov.cn'},
        {'name': '行政处罚-湖南省食品药品监督局', 'site': 'fda.hunan.gov.cn', "ignore": True,
         "tag": u"站点上有单条，有列表（格式不定），有图片，有文件，难以正确解析"},
        {'name': '行政处罚-天津市场和质量监督管理委员会', 'site': 'www.tjmqa.gov.cn'},
        {'name': '行政处罚-吉林食药品', 'site': 'www.jlfda.gov.cn'},
        {'name': '行政处罚-山西卫生计划局', 'site': 'www.sxwsjs.gov.cn'},
        {'name': '行政处罚-青海食品药品监督局', 'site': '125.72.41.16'},
        {'name': '行政处罚-湖南质监局', 'site': 'www.hn315.gov.cn', "ignore": True, "tag": u"站点无列表"},
        {'name': '行政处罚-北京食品药品监督局', 'site': 'www.bjda.gov.cn'},
        {'name': '行政处罚-浙江宁波环境保护局', 'site': 'www.nbepb.gov.cn'},
        {'name': '行政处罚-海南海口质量监督局', 'site': 'www.hkqtsb.gov.cn'},
        {'name': '行政处罚-陕西食药品监督', 'site': 'www.sxfda.gov.cn'},
        {'name': '行政处罚-湖北食药局', 'site': 'www.whfda.gov.cn'},
        {'name': '行政处罚-上海质监局', 'site': 'www.shzj.gov.cn'},
        {'name': '行政处罚-内蒙古食药品', 'site': 'www.nmfda.gov.cn', "ignore": True, "tag": u"详情页为文档和表格混合，不支持解析，不能入库"},
        {'name': '行政处罚-甘肃食药品', 'site': 'www.gstianzhu.gov.cn'},
        {'name': '行政处罚-重庆食品药品监督局', 'site': 'www.bnfda.gov.cn', "ignore": True, "tag": u"站点无法访问"},
        {'name': '行政处罚-贵州食品药品监督局', 'site': 'www.gzhfda.gov.cn'},
        {'name': '行政处罚-广西食品药品监督局', 'site': 'www.gxfda.gov.cn'},
        {'name': '行政处罚-北京技术质量监督网', 'site': 'www.bjtsb.gov.cn'},
    ]},
    "bid_detail": {"description": "招标信息", "sites": [
        {'name': '招投标—河南招标公告', 'site': 'www.hnsztb.com.cn'},
        {'name': '苏州市政府采购网', 'site': 'www.zfcg.suzhou.gov.cn'},
        {'name': '辽宁省招标投标监管网', 'site': 'www.lntb.gov.cn'},
        {'name': '福建招标与采购网', 'site': 'www.fjbid.gov.cn'},
        {'name': '中国山西政府采购--山西省财政厅主办', 'site': 'www.ccgp-shanxi.gov.cn'},
        {'name': '中国电子招标信息网_招标采购_专业的招投标信息平台', 'site': 'www.zbs365.com'},
        {'name': '甘肃经济信息网欢迎您！', 'site': 'www.gsei.com.cn'},
        {'name': '吉林省水利建设信息平台', 'site': 'www.jlssljsxx.com'},
        {'name': '内蒙古自治区政府采购网', 'site': 'www.nmgp.gov.cn'},
        {'name': '招中标-山东上善若水招标网', 'site': 'www.sdzbw.com', "ignore": True, "tag": u"页面内容为空"},
        {'name': '广西招标投标监督网', 'site': 'ztb.gxi.gov.cn'},
        {'name': '招投标－安徽', 'site': 'www.ahtba.org.cn', "ignore": True, "tag": u"内容页为post请求，无法配置"},
        {'name': '招投标－江西建设工程招标', 'site': 'www.jxjszbtb.com'},
        {'name': '天津招标投标网', 'site': 'www.tjztb.gov.cn', "ignore": True, "tag": u"站点无法访问"},
        {'name': '北京招投标公告网', 'site': 'www.bjztb.gov.cn'},
        {'name': '宁夏政府采购公共服务平台', 'site': 'www.ccgp-ningxia.gov.cn'},
        {'name': '中国招标信息网', 'site': 'www.cnbidding.com'},
        {'name': '吉林省建设项目招标网', 'site': 'jilinbidding.changchun.gov.cn'},
        {'name': '西藏自治区招标投标网', 'site': 'www.xzzbtb.gov.cn'},
        {'name': '广西壮族自治区政府采购网', 'site': 'www.gxzfcg.gov.cn'},
        {'name': '陕西省建设工程招标投标管理信息网', 'site': 'www.sxszbb.com'},
        {'name': '四川政府采购网', 'site': 'www.sczfcg.com'},
        {'name': '青海省招标投标信息网', 'site': 'qhzbtb.qhwszwdt.gov.cn'},
        {'name': '福建省政府采购网', 'site': 'cz.fjzfcg.gov.cn', "ignore": True, "tag": u"站点无法访问"},
        {'name': '招标-建筑网', 'site': 'zb.cbi360.net'},
        {'name': '招中标-黑龙江工程招标网', 'site': 'jx.hljztb.com'},
        {'name': '云南招标信息网', 'site': 'www.ynbidding.net', "ignore": True, "tag": u"站点无法访问"},
        {'name': '招投标-江西省招标投标网', 'site': 'www.jxtb.org.cn'},
        {'name': '招投标—重庆建设工程信息网', 'site': 'www1.cqjsxx.com'},
        {'name': '招标-福建建设工程电子招投标平台', 'site': 'www.fzztb.com'},
        {'name': '招中标-中国安装信息网', 'site': 'www.zgazxxw.com'},
        {'name': '河南招标投标网', 'site': 'www.hnzbtb.com'},
        {'name': '甘肃政府采购网', 'site': 'www.gszfcg.gansu.gov.cn'},
        {'name': '招投标-广东招标投标监管网', 'site': 'www.gdzbtb.gov.cn'},
        {'name': '招标-拉萨公共资源交易信息网', 'site': 'www.lsggzy.cn'},
        {'name': '贵州省招标投标公共服务平台', 'site': 'www.gzzbw.cn'},
        {'name': '招中标—河北项目网', 'site': 'www.hebpi.com'},
        {'name': '招中标-西藏自治区招标信息网', 'site': 'www.xzztb.org'},
        {'name': '中国国际招标网', 'site': 'www.chinabidding.com', "ignore": True, "tag": u"站点无法访问"},
        {'name': '山东政府采购网', 'site': 'www.ccgp-shandong.gov.cn'},
        {'name': '中国政府采购网-浙江省分网站 ', 'site': 'www.zjzfcg.gov.cn'},
        {'name': '招中标-新疆维吾尔自治区政府采购网', 'site': 'zfcg.xjcz.gov.cn'},
        {'name': '招中标-陕西采购与招标网', 'site': 'www.sntba.com'},
        {'name': '哈尔冰建设工程信息网', 'site': 'www.hrbjjzx.cn'},
        {'name': '中国采招网', 'site': 'www.bidcenter.com.cn', "ignore": True, "tag": u"数据只对会员开放"},
        {'name': '招中标—青海省政府采购网', 'site': 'www.ccgp-qinghai.gov.cn'},
        {'name': '招标-天津建设工程信息网', 'site': 'www.tjconstruct.cn'},
        {'name': '招投标－湖南－bidding', 'site': 'www.bidding.hunan.gov.cn'},
        {'name': '江苏政府采购网', 'site': 'www.ccgp-jiangsu.gov.cn'},
        {'name': '浙江招投标网', 'site': 'www.zjbid.cn'},
        {'name': '招中标-广东省财政厅网政府采购系统', 'site': 'www.gdgpo.gov.cn'},
        {'name': '广州市政府采购网', 'site': 'www.gzg2b.gov.cn'},
        {'name': '重庆招标信息网', 'site': 'www.cqzb.gov.cn'},
        {'name': '安徽省政府采购网', 'site': 'www.ahzfcg.gov.cn'},
        {'name': '招中标-河北建设工程信息网', 'site': 'www.hebgc.com'},
        {'name': '招投标-深圳市政府采购监管网', 'site': 'www.zfcg.sz.gov.cn'},
        {'name': '东莞公共资源交易网', 'site': 'www.dgzb.com.cn'},
        {'name': '广西招标网', 'site': 'www.guangxibid.com.cn'},
        {'name': '招投标—吉林市公共资源交易网', 'site': 'www.jlsggzyjy.gov.cn'},
        {'name': '招中标-海南省招标投标监管网', 'site': 'ztb.hainan.gov.cn'},
        {'name': '湖南政府采购网', 'site': 'www.ccgp-hunan.gov.cn', "ignore": True, "tag": u"站点无法访问"},
    ]},
    "ssgs_baseinfo": {"description": "上市公司基本信息表", "sites": [
        {'name': '巨潮资讯', 'site': 'www.cninfo.com.cn'},
    ]},
    "ssgs_notice_cninfo": {"description": "上市公告信息", "sites": [
        # {'name': '东方财富网', 'site': 'data.eastmoney.com', "ignore": True, "tag": u"采用巨潮咨询"},
        {'name': '巨潮资讯', 'site': 'www.cninfo.com.cn'},
    ]},
    "ssgs_caibao_profit": {"description": "上市公司财报-利润表", "sites": [
        {'name': '巨潮资讯', 'site': 'www.cninfo.com.cn'},
        # {'name': '东方财富网', 'site': 'www.eastmoney.com', "ignore": True, "tag": u"采用巨潮咨询"},
    ]},
    "ssgs_caibao_assets_liabilities": {"description": "上市公司财报-资产负债表", "sites": [
        {'name': '巨潮资讯', 'site': 'www.cninfo.com.cn'},
    ]},
    "ssgs_caibao_cash_flow": {"description": "上市公司财报-现金流量表", "sites": [
        {'name': '巨潮资讯', 'site': 'www.cninfo.com.cn'},
    ]},
    "ssgs_caibao_companies_ability": {"description": "上市公司财报-公司综合能力指标", "sites": [
        {'name': '巨潮资讯', 'site': 'www.cninfo.com.cn'},
    ]},
    "baidu_news": {"description": "百度新闻", "sites": [
        # {'name': '百度贴吧', 'site': 'tieba.baidu.com'},
        {'name': '百度新闻', 'site': 'news.baidu.com'},
    ]},
    "news": {"description": "新闻", "sites": [
        {'name': '新浪财经', 'site': 'finance.sina.com.cn'},
        {'name': '网易财经', 'site': 'money.163.com'},
        {'name': '凤凰财经网', 'site': 'finance.ifeng.com'},
        {'name': '网易新闻', 'site': 'news.163.com'},
        {'name': '腾讯财经', 'site': 'finance.qq.com'},
        {'name': '百度新闻', 'site': 'news.baidu.com', "ignore": True, "tag": u"站点不是自己的门户，没有规范链接"},
        {'name': '财经新闻频道', 'site': 'news.10jqka.com.cn'},
        {'name': '股票频道', 'site': 'stock.10jqka.com.cn'},
        {'name': '搜狐财经', 'site': 'business.sohu.com', "ignore": True, "tag": u"站点不是自己的门户，没有规范链接"},
        {'name': '新华社', 'site': 'news.xinhuanet.com'},
        {'name': '好买基金网', 'site': 'www.howbuy.com'},
        {'name': '云财经', 'site': 'www.yuncaijing.com'},
        {'name': '财经中心_中国网', 'site': 'finance.china.com.cn'},
        {'name': '东方财富网', 'site': 'finance.eastmoney.com'},
        {'name': '和讯财经新闻', 'site': 'news.hexun.com'},
        {'name': '和讯股票', 'site': 'stock.hexun.com'},
        {'name': '生意社', 'site': 'www.100ppi.com'},
        {'name': '南方财富网', 'site': 'www.southmoney.com'},
        {'name': '中证网', 'site': 'www.cs.com.cn'},
        {'name': '中金在线_市场股票频道', 'site': 'sc.stock.cnfol.com'},
        {'name': '建材资讯', 'site': 'news.jc001.cn'},
        {'name': '新浪网', 'site': 'news.sina.com.cn'},
        {'name': '全景网', 'site': 'www.p5w.net'},
        {'name': '和讯期货', 'site': 'futures.hexun.com'},
        {'name': '东方财富网_股票', 'site': 'stock.eastmoney.com'},
        {'name': '汇金网', 'site': 'www.gold678.com'},
        {'name': '金融界_股票频道', 'site': 'stock.jrj.com.cn'},
        {'name': '每经网', 'site': 'www.nbd.com.cn'},
        {'name': '凤凰资讯', 'site': 'news.ifeng.com'},
        {'name': '金投外汇网', 'site': 'forex.cngold.org'},
        {'name': '中国投资咨询网', 'site': 'www.ocn.com.cn'},
        {'name': '中商情报网', 'site': 'www.askci.com'},
    ]},
    "ppp_project": {"description": "ppp项目库", "sites": [
        {'name': '财政部PP项目库', 'site': 'www.cpppc.org'},
        {'name': '中国PPP服务平台', 'site': 'www.chinappp.cn'},
    ]},
    "land_auction": {"description": "土地招拍挂", "sites": [
        {'name': '土地市场网', 'site': 'www.landchina.com'},
    ]},
    "land_selling_auction": {"description": "土地基本信息", "sites": [
        {'name': '房天下', 'site': 'land.fang.com'},
    ]},
    "investment_institutions": {"description": "投资机构", "sites": [
        {'name': '私募通', 'site': 'org.pedata.cn'},
        {'name': 'IT橘子', 'site': 'www.itjuzi.com'},
        {'name': '投资界', 'site': 'zdb.pedaily.cn'},
    ]},

    "financing_events": {"description": "融资事件", "sites": [
        {'name': '私募通', 'site': 'need.pedata.cn'},
        {'name': 'IT橘子', 'site': 'www.itjuzi.com'},
        {'name': '投资界', 'site': 'zdb.pedaily.cn'},
    ]},

    "investment_funds": {"description": "投资基金", "sites": [
        {'name': '私募通', 'site': 'fund.pedata.cn'},
    ]},

    "investment_events": {"description": "投资事件", "sites": [
        {'name': '私募通', 'site': 'invest.pedata.cn'},
        {'name': '投资界', 'site': 'zdb.pedaily.cn'},
    ]},
    "exit_event": {"description": "退出事件", "sites": [
        {'name': '私募通', 'site': 'exit.pedata.cn'},
    ]},
    "acquirer_event": {"description": "并购事件", "sites": [
        {'name': '私募通', 'site': 'ma.pedata.cn'},
        {'name': '投资界', 'site': 'zdb.pedaily.cn'},
    ]},
    "listing_events": {"description": "上市事件", "sites": [
        {'name': '私募通', 'site': 'ipo.pedata.cn'},
    ]},
    "xiaoqu_lianjia": {"description": "房地产-小区-链家", "sites": [
        {'name': '链家', 'site': 'sz.lianjia.com'}
    ]},
    "xiaoqu_fangdd": {"description": "房地产-小区-房多多", "sites": [
        {'name': '房多多', 'site': 'esf.fangdd.com'}
    ]},
    "neighborhood_anjuke": {"description": "房地产-小区-安居客", "sites": [
        {'name': '安居客', 'site': 'www.anjuke.com', "ignore": True, "tag": u"站点反爬"}]},

    "loupan_lianjia": {"description": "房地产-楼盘-链家", "sites": [{'name': '链家楼盘', 'site': 'sz.lianjia.com'}]},
    "loupan_anjuke": {"description": "房地产-楼盘-安居客", "sites": [
        {'name': '安居客', 'site': 'sz.fang.anjuke.com', "ignore": True, "tag": u"站点反爬"}]},
    "loupan_fangdd": {"description": "房地产-楼盘-房多多", "sites": [{'name': '房多多', 'site': 'xf.fangdd.com'}]},

    "ershoufang_lianjia": {"description": "房地产-二手房-链家", "sites": [{'name': '链家', 'site': 'sz.lianjia.com'}]},
    "ershoufang_anjuke": {"description": "房地产-二手房-安居客", "sites": [
        {'name': '安居客', 'site': 'sz.fang.anjuke.com', "ignore": True, "tag": u"站点反爬"}]},
    "ershoufang_fangdd": {"description": "房地产-二手房-房多多", "sites": [{'name': '房多多', 'site': 'esf.fangdd.com'}]},

    "land_project_selling": {"description": "土地-项目转让", "sites": [
        {'name': '房天下', 'site': 'land.fang.com'}
    ]},
    "net_loan_blacklist": {"description": "网贷黑名单", "sites": [
        {'name': 'p2pblack', 'site': 'www.p2pblack.com', "ignore": True, "tag": u"站点无法访问"},
        {'name': '弘正道', 'site': 'www.chalaolai.com'},
        {'name': '贝才网', 'site': 'www.thebetterchinese.com'},
        {'name': '拍拍贷', 'site': 'www.ppdai.com', "ignore": True, "tag": u"站点均被重定向至首页"},
    ]},
}
